; *********************************************************
;
; 会計情報クラウド表示 Webアプリ設定ファイル
;
; *********************************************************

; マスターDBの接続情報
[adminDb]
hostName = "localhost"
dbName = "cloud_accounting_master"
userName = "admin"
password = "admin1201"

; 個別DBのホスト名
[hospitalDb]
hostName = "localhost"